using System.Diagnostics; using Xunit;
namespace Challenger.Siem.LinuxAgent.Tests;
public sealed class LinuxAgentTests
{
 [Fact] public async Task PlanIsNonMutatingAndSecretSafe(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var before=Directory.GetFileSystemEntries(root);var result=await Run("plan --root "+root);Assert.Equal(0,result.code);Assert.Contains("host policy changes: none",result.output);Assert.Equal(before,Directory.GetFileSystemEntries(root));Assert.DoesNotContain("ApiToken",result.output);Directory.Delete(root);}
 [Fact] public async Task SandboxLifecycleOwnsOnlyDeclaredPaths(){if(!OperatingSystem.IsLinux())return;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var payload=Path.Combine(root,"payload");Directory.CreateDirectory(payload);var binary=Path.Combine(payload,"Challenger.Siem.LinuxAgent");await File.WriteAllTextAsync(binary,"#!/bin/sh\n");File.SetUnixFileMode(binary,UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.UserExecute);var config=Path.Combine(root,"input.json");await File.WriteAllTextAsync(config,"{}");var install=await Run($"install --root {root} --payload {payload} --config {config} --no-service-control");Assert.Equal(0,install.code);Assert.Equal(UnixFileMode.UserRead|UnixFileMode.UserWrite,File.GetUnixFileMode(Path.Combine(root,"etc/challenger-siem-agent/agentsettings.json")));Assert.Equal(0,(await Run($"uninstall --root {root} --no-service-control")).code);Assert.True(Directory.Exists(payload));Assert.True(File.Exists(config));Directory.Delete(root,true);}
 [Fact] public async Task PackagingLetsOnlyTheDedicatedIdentityPersistItsCredential(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));var unit=await File.ReadAllTextAsync(Path.Combine(Repo,"packaging/linux/challenger-siem-agent.service"));Assert.Contains("chown -R challenger-siem:challenger-siem \"$etc\" \"$state\"",script);Assert.Contains("ReadWritePaths=/etc/challenger-siem-agent /var/lib/challenger-siem-agent",unit);Assert.Contains("User=challenger-siem",unit);}
 static string Repo=>Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../../"));
 static async Task<(int code,string output)> Run(string args){var p=Process.Start(new ProcessStartInfo("bash",$"{Repo}/scripts/linux-agent.sh {args}"){RedirectStandardOutput=true,RedirectStandardError=true})!;var text=await p.StandardOutput.ReadToEndAsync()+await p.StandardError.ReadToEndAsync();await p.WaitForExitAsync();return(p.ExitCode,text);}
}
