using System.Diagnostics; using Xunit;
namespace Challenger.Siem.LinuxAgent.Tests;
public sealed class LinuxAgentTests
{
 [Fact] public async Task PlanIsNonMutatingAndSecretSafe(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var before=Directory.GetFileSystemEntries(root);var result=await Run("plan --root "+root);Assert.Equal(0,result.code);Assert.Contains("base install changes none",result.output);Assert.Equal(before,Directory.GetFileSystemEntries(root));Assert.DoesNotContain("ApiToken",result.output);Directory.Delete(root);}
 [Fact] public async Task SandboxLifecycleOwnsOnlyDeclaredPaths(){if(!OperatingSystem.IsLinux())return;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var payload=Path.Combine(root,"payload");Directory.CreateDirectory(payload);var binary=Path.Combine(payload,"Challenger.Siem.LinuxAgent");await File.WriteAllTextAsync(binary,"#!/bin/sh\n");File.SetUnixFileMode(binary,UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.UserExecute);var config=Path.Combine(root,"input.json");await File.WriteAllTextAsync(config,"{}");var install=await Run($"install --root {root} --payload {payload} --config {config} --no-service-control");Assert.Equal(0,install.code);Assert.Equal(UnixFileMode.UserRead|UnixFileMode.UserWrite,File.GetUnixFileMode(Path.Combine(root,"etc/challenger-siem-agent/agentsettings.json")));Assert.Equal(0,(await Run($"uninstall --root {root} --no-service-control")).code);Assert.True(Directory.Exists(payload));Assert.True(File.Exists(config));Directory.Delete(root,true);}
 [Fact] public async Task SandboxUpgradeCanPreserveTheInstalledProtectedConfiguration(){if(!OperatingSystem.IsLinux())return;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var payload=Path.Combine(root,"payload");Directory.CreateDirectory(payload);var binary=Path.Combine(payload,"Challenger.Siem.LinuxAgent");await File.WriteAllTextAsync(binary,"#!/bin/sh\n");File.SetUnixFileMode(binary,UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.UserExecute);var config=Path.Combine(root,"input.json");await File.WriteAllTextAsync(config,"{\"ApiToken\":\"synthetic-secret\"}");Assert.Equal(0,(await Run($"install --root {root} --payload {payload} --config {config} --no-service-control")).code);var installedConfig=Path.Combine(root,"etc/challenger-siem-agent/agentsettings.json");var upgrade=await Run($"upgrade --root {root} --payload {payload} --config {installedConfig} --no-service-control");Assert.Equal(0,upgrade.code);Assert.Contains("preserving it in place",upgrade.output);Assert.Equal("{\"ApiToken\":\"synthetic-secret\"}",await File.ReadAllTextAsync(installedConfig));Directory.Delete(root,true);}
 [Fact] public async Task PackagingLetsOnlyTheDedicatedIdentityPersistItsCredential(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));var unit=await File.ReadAllTextAsync(Path.Combine(Repo,"packaging/linux/challenger-siem-agent.service"));Assert.Contains("chown -R challenger-siem:challenger-siem \"$etc\" \"$state\"",script);Assert.Contains("ReadWritePaths=/etc/challenger-siem-agent /var/lib/challenger-siem-agent",unit);Assert.Contains("User=challenger-siem",unit);Assert.Contains("NoNewPrivileges=yes",unit);Assert.Contains("CapabilityBoundingSet=",unit);Assert.DoesNotContain("MemoryDenyWriteExecute=yes",unit);}
 [Fact] public async Task OptionalProcessVisibilityProfileIsExplicitAndSyscallRestricted(){var profile=await File.ReadAllTextAsync(Path.Combine(Repo,"packaging/linux/challenger-siem-agent-process-visibility.conf"));var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));Assert.Contains("CapabilityBoundingSet=CAP_SYS_PTRACE",profile);Assert.Contains("AmbientCapabilities=CAP_SYS_PTRACE",profile);Assert.Contains("SystemCallFilter=~ptrace process_vm_readv process_vm_writev kcmp pidfd_getfd perf_event_open",profile);Assert.DoesNotContain("CAP_SYS_ADMIN",profile);Assert.Contains("must contain only CAP_SYS_PTRACE",script);Assert.Contains("required.issubset(tokens)",script);Assert.Contains("value != (1 << 19)",script);}
 [Fact] public async Task ProcessVisibilityProfileRequiresExplicitConfigAndSupportsAlternateRootRollback(){if(!OperatingSystem.IsLinux())return;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var unitDir=Path.Combine(root,"etc/systemd/system");Directory.CreateDirectory(unitDir);await File.WriteAllTextAsync(Path.Combine(unitDir,"challenger-siem-agent.service"),"[Service]\nUser=challenger-siem\n");var config=Path.Combine(root,"approved.json");await File.WriteAllTextAsync(config,"{\"Agent\":{\"PassiveTelemetry\":{\"CrossUserExecutableVisibility\":true}}}");var plan=await Run($"process-visibility-plan --root {root} --config {config} --no-service-control");Assert.Equal(0,plan.code);Assert.Contains("add only CAP_SYS_PTRACE",plan.output);var enable=await Run($"process-visibility-enable --root {root} --config {config} --no-service-control");Assert.Equal(0,enable.code);Assert.Equal(0,(await Run($"process-visibility-validate --root {root} --no-service-control")).code);Assert.Equal(0,(await Run($"process-visibility-disable --root {root} --no-service-control")).code);Assert.False(File.Exists(Path.Combine(unitDir,"challenger-siem-agent.service.d/30-process-executable-visibility.conf")));Directory.Delete(root,true);}
 [Fact] public async Task ReadOnlyValidationDoesNotRequireMutationPreflight(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));Assert.Contains("validate(){\n  # Validation is read-only.",script);Assert.Contains("preflight plan",script);}
 [Fact] public async Task L4PlanRunsFromTheServiceOwnedStateDirectory(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));Assert.Contains("cd \"$state\"\n      runuser -u challenger-siem",script);Assert.Contains("cd \"$state\"\n    env -i",script);}
 [Fact] public async Task UpgradePlanningPrefersThePublishedCandidateBinary(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));var functionStart=script.IndexOf("l4_telemetry_binary(){",StringComparison.Ordinal);var payloadCheck=script.IndexOf("if [[ -n $payload && -x $payload/Challenger.Siem.LinuxAgent ]]",functionStart,StringComparison.Ordinal);var installedCheck=script.IndexOf("elif [[ -x $opt/Challenger.Siem.LinuxAgent ]]",functionStart,StringComparison.Ordinal);Assert.True(functionStart>=0&&payloadCheck>functionStart&&installedCheck>payloadCheck);}
 [Fact] public async Task PackagingValidatesTheLockedNoLoginIdentityBeforeCreatingPaths(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/linux-agent.sh"));Assert.Contains("validate_service_identity(){",script);Assert.Contains("must be non-root",script);Assert.Contains("must use a non-login shell",script);Assert.Contains("must have a locked, non-reusable password",script);var install=script.IndexOf("install(){",StringComparison.Ordinal);var identity=script.IndexOf("validate_service_identity true || {",install,StringComparison.Ordinal);var create=script.IndexOf("mkdir -p -m 0755",install,StringComparison.Ordinal);Assert.True(install>=0&&identity>install&&create>identity);}
 [Fact] public async Task PublishBundleRejectsTrackedOrNonEmptyOutput(){var script=await File.ReadAllTextAsync(Path.Combine(Repo,"scripts/publish-linux-agent.sh"));Assert.Contains("git check-ignore -q",script);Assert.Contains("publish output must be empty",script);Assert.Contains("credential-bearing files",script);}
 [Fact] public async Task SelfContainedAgentDoesNotRequireTargetIcu(){var project=await File.ReadAllTextAsync(Path.Combine(Repo,"agent/LinuxAgent/LinuxAgent.csproj"));Assert.Contains("<InvariantGlobalization>true</InvariantGlobalization>",project);}
 [Fact] public async Task AgentSuppressesSelfCollectingHttpInformationLogs(){var program=await File.ReadAllTextAsync(Path.Combine(Repo,"agent/LinuxAgent/Program.cs"));Assert.Contains("AddFilter(\"System.Net.Http.HttpClient\", LogLevel.Warning)",program);Assert.Contains("feedback loop",program,StringComparison.OrdinalIgnoreCase);}
 [Fact] public async Task SandboxInstallRejectsSymlinkTargetsBeforeMutation(){if(!OperatingSystem.IsLinux())return;var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var payload=Path.Combine(root,"payload");var unrelated=Path.Combine(root,"unrelated");Directory.CreateDirectory(payload);Directory.CreateDirectory(unrelated);Directory.CreateDirectory(Path.Combine(root,"opt"));Directory.CreateSymbolicLink(Path.Combine(root,"opt/challenger-siem-agent"),unrelated);var binary=Path.Combine(payload,"Challenger.Siem.LinuxAgent");await File.WriteAllTextAsync(binary,"#!/bin/sh\n");File.SetUnixFileMode(binary,UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.UserExecute);var config=Path.Combine(root,"input.json");await File.WriteAllTextAsync(config,"{}");var install=await Run($"install --root {root} --payload {payload} --config {config} --no-service-control");Assert.NotEqual(0,install.code);Assert.Contains("Product target is a symlink",install.output);Assert.Empty(Directory.GetFileSystemEntries(unrelated));Directory.Delete(root,true);}
 static string Repo=>Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../../"));
 static async Task<(int code,string output)> Run(string args){var p=Process.Start(new ProcessStartInfo("bash",$"{Repo}/scripts/linux-agent.sh {args}"){RedirectStandardOutput=true,RedirectStandardError=true})!;var text=await p.StandardOutput.ReadToEndAsync()+await p.StandardError.ReadToEndAsync();await p.WaitForExitAsync();return(p.ExitCode,text);}
}
