#!/usr/bin/env bash
set -euo pipefail
mode=${1:-plan}; shift || true
root=/; payload=; config=; no_service=false
while (($#)); do case "$1" in --root) root=$2;shift 2;;--payload) payload=$2;shift 2;;--config) config=$2;shift 2;;--no-service-control) no_service=true;shift;;*) echo "Unknown option: $1" >&2;exit 2;;esac;done
case "$mode" in plan|install|upgrade|validate|uninstall) ;; *) echo "Usage: $0 plan|install|upgrade|validate|uninstall" >&2;exit 2;;esac
p(){ [[ $root == / ]]&&printf '%s' "$1"||printf '%s%s' "${root%/}" "$1"; }
opt=$(p /opt/challenger-siem-agent); etc=$(p /etc/challenger-siem-agent); state=$(p /var/lib/challenger-siem-agent); unit=$(p /etc/systemd/system/challenger-siem-agent.service)
preflight(){ [[ $(uname -s) == Linux ]]||{ echo 'Unsupported platform: Linux is required.' >&2;return 1;};case $(uname -m) in x86_64|aarch64) ;;*) echo 'Unsupported architecture.' >&2;return 1;;esac;[[ $root != / || -d /run/systemd/system ]]||{ echo 'Unsupported init: systemd is required.' >&2;return 1;};[[ $root != / || $EUID -eq 0 ]]||{ echo 'Administrative execution is required for mutation.' >&2;return 1;}; }
plan(){ echo 'Challenger SIEM Linux Agent plan (read-only)';echo "binary: $opt";echo "configuration (0600): $etc/agentsettings.json";echo "private state/queue (0700): $state";echo "unit: $unit";echo 'identity: challenger-siem (locked, no login); capabilities: none';echo 'host policy changes: none (audit/firewall/authentication/kernel/security policy untouched)'; }
validate(){ preflight;[[ -x $opt/Challenger.Siem.LinuxAgent ]]||{ echo 'agent binary missing' >&2;return 1;};[[ -f $etc/agentsettings.json && $(stat -c %a "$etc/agentsettings.json") == 600 ]]||{ echo 'configuration missing or not mode 0600' >&2;return 1;};[[ -f $unit ]]||{ echo 'unit missing' >&2;return 1;};grep -q '^User=challenger-siem$' "$unit";! grep -Eq 'Token|Password|ApiToken|EnrollmentToken' "$unit";echo 'validation passed';}
install(){ preflight;[[ -n $payload && -x $payload/Challenger.Siem.LinuxAgent ]]||{ echo 'A published executable payload is required.' >&2;return 1;};[[ -n $config && -f $config ]]||{ echo 'A configuration file is required.' >&2;return 1;};[[ $root != / || $(stat -c %a "$config") == 600 ]]||{ echo 'Configuration input must be mode 0600.' >&2;return 1;};[[ $root != / || $(id -u challenger-siem 2>/dev/null || true) ]]||{ echo 'Dedicated challenger-siem identity must exist; create it explicitly before install.' >&2;return 1;};mkdir -p -m 0755 "$opt" "$(dirname "$unit")";mkdir -p -m 0700 "$etc" "$state";command install -m 0755 "$payload/Challenger.Siem.LinuxAgent" "$opt/Challenger.Siem.LinuxAgent";command install -m 0600 "$config" "$etc/agentsettings.json";command install -m 0644 "$(dirname "$0")/../packaging/linux/challenger-siem-agent.service" "$unit";if [[ $root == / ]];then chown -R root:root "$opt" "$etc";chown -R challenger-siem:challenger-siem "$state";fi;if ! $no_service && [[ $root == / ]];then systemctl daemon-reload;systemctl enable --now challenger-siem-agent.service;fi;validate;}
uninstall(){ preflight;if ! $no_service && [[ $root == / ]];then systemctl disable --now challenger-siem-agent.service || true;fi;rm -f "$unit";rm -rf "$opt" "$etc" "$state";if ! $no_service && [[ $root == / ]];then systemctl daemon-reload;fi;echo 'project-owned files removed; service identity retained';}
case "$mode" in plan) preflight;plan;;install|upgrade) install;;validate) validate;;uninstall) uninstall;;esac
