using Challenger.Siem.Contracts.V2;

namespace Challenger.Siem.Api.Detections;

public static class DetectionRuleCatalog
{
    private const int DefaultWindowSeconds = 900;

    public static IReadOnlyList<DetectionRuleMetadata> BuiltInRules { get; } = new[]
    {
        LinuxRule(
            "auth.bruteforce.linux",
            "Repeated Linux authentication failures",
            "Detects repeated Linux login or SSH authentication failures for the same account or remote address.",
            DetectionSeverities.High,
            "authentication",
            "linux-login-session,linux-ssh",
            "target_user_name,source_ip,outcome",
            "T1110",
            "credential-access",
            900,
            "agent_id,source_ip,target_user_name",
            "Expected during password-spray simulations, vulnerability scans, or mistyped credentials from known administration hosts.",
            "Review the source address and target account, validate MFA/lockout posture, inspect surrounding SSH/PAM events, and block or rotate credentials only through approved host procedures."),
        LinuxRule(
            "auth.success-after-failures.linux",
            "Linux authentication success after failures",
            "Detects a successful Linux login or SSH authentication shortly after multiple failures for the same account or remote address.",
            DetectionSeverities.High,
            "authentication",
            "linux-login-session,linux-ssh",
            "target_user_name,source_ip,outcome",
            "T1110,T1078",
            "credential-access,defense-evasion",
            1800,
            "agent_id,source_ip,target_user_name",
            "Common after legitimate password resets or administrators correcting mistyped credentials.",
            "Confirm the successful login owner and source, review privilege activity after the login, and preserve exact evidence event IDs for follow-up."),
        LinuxRule(
            "privilege.sudo-su-root.linux",
            "Linux sudo or su privileged session",
            "Detects sudo command execution or su session activity targeting root or another privileged account.",
            DetectionSeverities.High,
            "authorization",
            "linux-sudo-su",
            "user_name,target_user_name,process_command_line,outcome",
            "T1548.003,T1078",
            "privilege-escalation",
            900,
            "agent_id,user_name,target_user_name,process_image",
            "Expected for approved administrative maintenance windows and configuration-management accounts.",
            "Verify the initiating user, command, change window, and follow-on package/service/firewall activity before escalating."),
        LinuxRule(
            "ssh.root-login.linux",
            "Linux SSH root or privileged login",
            "Detects successful SSH authentication or session start for root or another privileged account.",
            DetectionSeverities.High,
            "authentication",
            "linux-ssh",
            "target_user_name,source_ip,outcome",
            "T1078.004",
            "initial-access,privilege-escalation",
            900,
            "agent_id,source_ip,target_user_name",
            "May be expected on break-glass hosts that explicitly permit direct root SSH.",
            "Validate whether direct privileged SSH is approved, inspect session activity, and prefer policy review over automated host mutation."),
        LinuxRule(
            "process.suspicious-privileged-command.linux",
            "Suspicious privileged Linux command",
            "Detects sudo/su command lines with download, encoded shell, netcat, chmod, or interpreter chaining patterns using structured command fields.",
            DetectionSeverities.High,
            "process",
            "linux-sudo-su",
            "user_name,process_command_line,process_image",
            "T1059,T1105,T1204",
            "execution,command-and-control",
            900,
            "agent_id,user_name,process_command_line",
            "Security tests, package bootstrap scripts, and approved automation can use curl, wget, chmod, or shell wrappers.",
            "Inspect the exact command, parent user, package/service changes, network destination context, and whether the host role permits this automation."),
        LinuxRule(
            "process.suspicious-snapshot-command.linux",
            "Suspicious command observed in Linux process snapshot",
            "Detects conservative download-to-shell, reverse-shell, encoded execution, or chained download-and-execute patterns in structured command lines from process snapshot polling.",
            DetectionSeverities.High,
            "process",
            "linux-process-snapshot-diff",
            "process_command_line,process_image,action",
            "T1059,T1105",
            "execution,command-and-control",
            900,
            "agent_id,process_image,process_command_line",
            "Approved bootstrap tooling, security tests, and incident-response utilities can use these patterns. Snapshot polling can first observe an already-running process and does not establish its exact execution time or ancestry.",
            "Review the exact structured command, executable, user and nearby process/network snapshot evidence. Confirm timing with authoritative logs before containment; do not infer an exec event from polling alone."),
        LinuxRule(
            "persistence.service-start.linux",
            "Linux service change or new unit activity",
            "Detects Linux service start/reload/failure events that can indicate new or modified persistence.",
            DetectionSeverities.Medium,
            "service",
            "linux-service-change",
            "service_name,action,outcome",
            "T1543.002,T1569.002",
            "persistence,execution",
            1800,
            "agent_id,service_name,action",
            "Expected during package installation, boot, patching, and service restarts.",
            "Correlate with package and administrative activity, verify the unit path/configuration through approved review channels, and do not restart/remediate from SIEM workflow.",
            version: 2),
        LinuxRule(
            "persistence.scheduler-activity.linux",
            "Linux cron or systemd timer activity",
            "Detects cron job execution or systemd timer triggers that may represent scheduled persistence.",
            DetectionSeverities.Medium,
            "scheduler",
            "linux-cron-timers",
            "task_name,service_name,action",
            "T1053.003,T1053.006",
            "persistence,execution",
            1800,
            "agent_id,service_name,task_name,action",
            "Expected for routine cron maintenance, timers, backups, and monitoring agents.",
            "Review the job/timer identity, owner, recent package or file changes, and whether timing aligns with expected maintenance.",
            version: 2),
        LinuxRule(
            "package.change.linux",
            "Linux package installed, updated, or removed",
            "Detects Linux package-management changes that can introduce tooling, persistence, or security-control drift.",
            DetectionSeverities.Medium,
            "package",
            "linux-package-management,linux-package-inventory-diff",
            "package_name,action,outcome",
            "T1546,T1072",
            "persistence,defense-evasion",
            3600,
            "agent_id,package_name,action",
            "Expected during patch windows, image builds, and configuration-management runs.",
            "Confirm the package/change source, compare with approved maintenance, and correlate with new service, scheduler, firewall, or kernel events.",
            version: 2),
        LinuxRule(
            "kernel.security-control-change.linux",
            "Linux kernel or security-control change",
            "Detects kernel module, LSM, or security-control journal events that may change host protection posture.",
            DetectionSeverities.High,
            "kernel_security",
            "linux-kernel-security",
            "action,outcome,service_name,file_path",
            "T1562.001,T1547.006",
            "defense-evasion,persistence",
            1800,
            "agent_id,action,service_name,file_path",
            "Expected for signed kernel updates, driver/module loading during boot, and known AppArmor/SELinux denials.",
            "Review module/control identity, package context, and whether the event represents a denied attempt or an effective control change."),
        LinuxRule(
            "policy.security-posture-drift.linux",
            "Linux security posture drift",
            "Detects a post-baseline change in an approval-gated Linux L4 security-posture fingerprint. Baseline, sample, gap, and restored records are non-alerting.",
            DetectionSeverities.High,
            "policy_posture",
            "linux-policy-posture-drift",
            "event_code,action",
            "T1562.001,T1098",
            "defense-evasion,persistence",
            3600,
            "agent_id,event_code",
            "Expected after an approved firewall, mandatory-access-control, Secure Boot, SSH, or agent-integrity posture change. Fingerprints establish change evidence, not the exact changed value.",
            "Review the bounded posture snapshot type and approval/change window, correlate package/service/privilege evidence, and inspect authoritative host policy only through an approved procedure."),
        LinuxRule(
            "firewall.change.linux",
            "Linux firewall policy or traffic decision",
            "Detects Linux firewall allow, deny, or policy-change events when firewall logging is already enabled.",
            DetectionSeverities.Medium,
            "firewall",
            "linux-firewall",
            "source_ip,destination_ip,destination_port,protocol,action",
            "T1562.004,T1090",
            "defense-evasion,command-and-control",
            1800,
            "agent_id,source_ip,destination_ip,destination_port,action",
            "Expected on hosts with verbose firewall logging, rule deployments, or known noisy deny traffic.",
            "Confirm whether the rule/traffic is expected, correlate with service and package changes, and avoid changing firewall policy from this workflow."),
        LinuxRule(
            "network.listener-observed.linux",
            "Non-loopback Linux listener observed",
            "Reports a non-loopback or wildcard listening socket observed or changed by bounded procfs snapshot polling; it is not a kernel bind event and any plan-approved process attribution can remain partial.",
            DetectionSeverities.Low,
            "network",
            "linux-network-socket-snapshot-diff",
            "source_ip,source_port,protocol,action",
            "T1049",
            "discovery",
            3600,
            "agent_id,source_ip,source_port,protocol",
            "Ordinary post-baseline service starts can create expected listener noise. Initial baseline establishment is non-alerting; polling can miss short-lived sockets and cannot prove exact bind time or packet activity. Ownership may be stale, capped, denied, or ambiguous.",
            "Compare the address and port with the approved host role, bounded ownership confidence, and prior snapshots, then correlate service/package telemetry. Treat this as polling evidence and verify with authoritative host data before response."),
        LinuxRule(
            "behavior.host-resource-pressure.linux",
            "Severe Linux host resource pressure sample",
            "Detects bounded procfs samples showing at least 95% CPU busy, at most 5% available memory, multiple blocked processes, or severe 10-second PSI pressure.",
            DetectionSeverities.Medium,
            "host_behavior",
            "linux-host-behaviour-metrics",
            "action,cpu_busy_permille,memory_total_bytes,memory_available_bytes,processes_blocked,cpu_pressure_some_avg10_milli,memory_pressure_some_avg10_milli,io_pressure_some_avg10_milli",
            "T1496,T1499",
            "impact",
            900,
            "agent_id,event_code",
            "Short load tests, builds, backups, memory reclamation, and storage bursts can exceed a threshold for one coalesced sample. Missing polling intervals are not backfilled and a single sample does not prove sustained impact.",
            "Review consecutive bounded samples, queue/source health, workload changes, bounded whole-device diagnostics, and nearby process evidence. Confirm sustained pressure through approved host monitoring before taking disruptive action.",
            version: 2),
        LinuxRule(
            "tamper.agent-log-source-silence.linux",
            "Linux agent/log tamper or source-health gap",
            "Detects agent configuration changes, journal corruption/gaps, source silence, permission loss, or throttled source-health events when reported.",
            DetectionSeverities.Critical,
            "tamper",
            "linux-agent-log-tamper,agent-health",
            "event_code,action,outcome,source_id",
            "T1070.002,T1562.001,T1562.006",
            "defense-evasion",
            900,
            "agent_id,source_id,event_code,action",
            "Expected during agent upgrades, log rotation tests, permission reviews, or synthetic source-health validation.",
            "Treat as a visibility gap, preserve event/source-health evidence, verify queue and source status, and do not assume absence of malicious activity during the gap."),
        LinuxRule(
            "tamper.agent-self-integrity.linux",
            "Linux agent self-integrity change",
            "Detects approved self-integrity snapshot or inventory-diff telemetry for Challenger SIEM agent binary, unit, configuration metadata, or state directory changes.",
            DetectionSeverities.High,
            "tamper",
            "linux-agent-self-integrity-snapshot,inventory-diff,agent-health",
            "file_path,hash,event_code,action",
            "T1562.001,T1036",
            "defense-evasion,persistence",
            3600,
            "agent_id,file_path,event_code",
            "Expected during approved agent install, upgrade, repair, packaging validation, or service-unit maintenance.",
            "Validate against the approved package/configuration plan, compare fingerprint metadata, and preserve local evidence under ignored or runtime paths only."),
        LinuxRule(
            "tamper.agent-heartbeat-loss.linux",
            "Linux agent heartbeat loss",
            "Created by the server liveness monitor after three inferred heartbeat intervals bounded to two through fifteen minutes.",
            DetectionSeverities.Critical,
            "tamper",
            "agent-health",
            "agent_id",
            "T1562.001",
            "defense-evasion",
            900,
            "agent_id",
            "Expected during an approved agent stop, host shutdown, service restart, or API/database outage.",
            "Verify agent and platform service health independently. A new authenticated heartbeat resolves the outage alert without assigning disposition or closing it."),
        LinuxRule(
            "tamper.audit-policy-change.linux",
            "Linux audit policy tampering",
            "Detects normalized audit-policy change evidence from the approval-gated journal-backed audit router.",
            DetectionSeverities.Critical,
            "tamper",
            "linux-audit-framework",
            "action,outcome",
            "T1562.001",
            "defense-evasion",
            900,
            "agent_id,action",
            "Expected only during separately approved audit policy maintenance.",
            "Validate the policy change and approval window. Audit collection never changes rules or producer configuration."),
        LinuxRule(
            "tamper.audit-health-degraded.linux",
            "Linux audit health degraded",
            "Detects a trusted bounded audit-health sample reporting a stopped or disabled audit facility, lost records, or high kernel backlog.",
            DetectionSeverities.Critical,
            "tamper",
            "linux-audit-framework",
            "event_code,action,outcome,audit.loss_state,audit.backlog_state",
            "T1562.001,T1070.002",
            "defense-evasion",
            900,
            "agent_id,event_code,audit.loss_state,audit.backlog_state",
            "Expected briefly during separately approved audit service maintenance or a controlled audit-policy reload.",
            "Preserve the health event and source status, verify auditd and kernel audit status through an approved read-only procedure, and investigate the visibility interval before changing policy."),
        LinuxRule(
            "persistence.audited-sensitive-file-change.linux",
            "Audited sensitive Linux file change",
            "Detects successful Audit Framework syscall evidence tagged by the managed Challenger identity, privilege, persistence, SSH, package-policy, kernel-policy, SIEM-integrity, or audit-policy watches.",
            DetectionSeverities.High,
            "persistence",
            "linux-audit-framework",
            "action,file_path,audit.rule_key",
            "T1098,T1543.002,T1546,T1556",
            "persistence,privilege-escalation,defense-evasion",
            1800,
            "agent_id,file_path,audit.rule_key",
            "Expected during approved account, sudo, SSH, service, scheduler, package-policy, kernel-policy, audit-policy, or Challenger SIEM maintenance.",
            "Validate the retained path and audit rule key against an approved change, then correlate the numeric identity, executable, package, service, and authentication evidence."),
        LinuxRule(
            "kernel.audited-security-syscall.linux",
            "Audited Linux kernel-control syscall",
            "Detects successful module or kexec control syscalls tagged by the managed Challenger kernel audit rule.",
            DetectionSeverities.High,
            "kernel_security",
            "linux-audit-framework",
            "action,audit.rule_key,audit.syscall",
            "T1547.006,T1562.001",
            "persistence,defense-evasion",
            1800,
            "agent_id,audit.syscall",
            "Expected during approved kernel, driver, boot, or low-level security tooling maintenance.",
            "Correlate the syscall number, executable, numeric identity, package activity, kernel journal, and approved maintenance window before escalation."),
        LinuxRule(
            "process.temporary-deleted-execution.linux",
            "Temporary, deleted, or memfd Linux execution",
            "Detects post-baseline process snapshots whose executable is deleted, memfd-backed, or under a bounded temporary path.",
            DetectionSeverities.High,
            "process",
            "linux-process-snapshot-diff",
            "action,process_image",
            "T1055,T1204",
            "execution,defense-evasion",
            900,
            "agent_id,process_image",
            "Updaters and temporary build tooling may legitimately replace or execute files in temporary paths.",
            "Review process ownership, command evidence, package activity, and socket attribution; polling does not establish exact execution time."),
        LinuxRule(
            "privilege.dangerous-effective-capabilities.linux",
            "Dangerous Linux effective capabilities",
            "Detects post-baseline process snapshots with decoded high-risk effective capability bits.",
            DetectionSeverities.High,
            "authorization",
            "linux-process-snapshot-diff",
            "action,process.dangerous_effective_capabilities",
            "T1548",
            "privilege-escalation",
            900,
            "agent_id,process_image,process.dangerous_effective_capabilities",
            "Container runtimes, networking daemons, and approved administration tools can require high-risk capabilities.",
            "Validate the executable, service provenance, user, and expected capability boundary before response.")
    };

    public static bool IsLinuxRule(string ruleId) => ruleId.EndsWith(".linux", StringComparison.OrdinalIgnoreCase);

    private static DetectionRuleMetadata LinuxRule(
        string id,
        string name,
        string description,
        string severity,
        string category,
        string requiredSources,
        string requiredFields,
        string mitre,
        string tactics,
        int windowSeconds,
        string suppressionKeys,
        string falsePositiveNotes,
        string responseGuidance,
        int version = 1) => Rule(
            id,
            name,
            description,
            severity,
            category,
            requiredSources,
            requiredFields,
            mitre,
            tactics,
            windowSeconds,
            suppressionKeys,
            falsePositiveNotes,
            responseGuidance,
            version);

    private static DetectionRuleMetadata Rule(
        string id,
        string name,
        string description,
        string severity,
        string category,
        string requiredSources,
        string requiredFields,
        string mitre,
        string? tactics = null,
        int windowSeconds = DefaultWindowSeconds,
        string? suppressionKeys = null,
        string? falsePositiveNotes = null,
        string? responseGuidance = null,
        int version = 1) => new()
        {
            RuleId = id,
            Version = version,
            Name = name,
            Description = description,
            Severity = severity,
            Confidence = "medium",
            Category = category,
            RequiredSources = Split(requiredSources),
            RequiredFields = Split(requiredFields),
            MitreAttack = Split(mitre),
            Tactics = Split(string.IsNullOrWhiteSpace(tactics) ? InferTactics(category) : tactics),
            CorrelationWindowSeconds = windowSeconds,
            SuppressionKeys = Split(string.IsNullOrWhiteSpace(suppressionKeys) ? requiredFields : suppressionKeys),
            FalsePositiveNotes = falsePositiveNotes ?? "Expected administrative activity can match this rule; validate with source-health and change context before escalation.",
            ResponseGuidance = responseGuidance ?? "Review exact evidence events, verify prerequisite source health, correlate nearby activity, and follow approved administrative runbooks.",
            Enabled = true
        };

    private static string InferTactics(string category) => category.ToLowerInvariant() switch
    {
        "authentication" => "credential-access,initial-access",
        "account" => "persistence,privilege-escalation",
        "powershell" or "process" => "execution,defense-evasion",
        "credential_access" => "credential-access",
        "persistence" or "service" or "scheduler" => "persistence,execution",
        "tamper" => "defense-evasion",
        "malware" => "execution,impact",
        "network" or "firewall" => "command-and-control,defense-evasion",
        "impact" => "impact",
        "package" => "persistence,defense-evasion",
        "kernel_security" => "defense-evasion,persistence",
        "coverage" => "defense-evasion",
        _ => "discovery"
    };

    private static IReadOnlyList<string> Split(string value) => string.IsNullOrWhiteSpace(value)
        ? Array.Empty<string>()
        : value.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
}
